### ISSUE TITLE
[Bug]: Audio Pro speakers do not show metadata

### ISSUE THREAD

**Issue by bootsofglory** [mjcumming/wiim#101]
### Pre-submission Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I am using the latest version of the WiiM integration
- [x] I have enabled debug logging and included relevant logs below

### Integration Version

0.2.18

### Home Assistant Version

2025.11.1

### WiiM Device Model

Other LinkPlay device

### Bug Description

When playing music on Audio Pro speakers (e.g: playing music via the WiiM app), the speaker entity does not show information about what's playing. In fact, Home Assistant does not register anything as playing at all on the speaker - instead its state just reads as "Idle".

Pressing play on the speaker in Home Assistant while something is already playing on the speaker restarts the song and changes the state to "playing" (though still without any metadata) for a short while, after which it reverts to "idle".

### Steps to Reproduce

1. Add speaker to HA
2. Play music on speaker (e.g: through WiiM app)
3. Examine entity data on HA

### Configuration

```yaml

```

### Debug Logs

[home-assistant_wiim_2025-11-07T18-09-54.318Z.log](https://github.com/user-attachments/files/23423631/home-assistant_wiim_2025-11-07T18-09-54.318Z.log)

### Installation Method

HACS

**Comment by mjcumming** [comment]
Hi, give 2.19 a try - this should grab the upnp events properly.

**Comment by bootsofglory** [comment]
No luck I'm afraid. I also notice that when playing music from Home Assistant, no metadata shows up in the WiiM app either (though the speaker does show as playing and the track length seems to be there but the player position doesn't update).

**Comment by mjcumming** [comment]
ok, a few more updates to UPnP handling - it's tricky combining HTTP/UPnP and idiosyncrasies between LinkPlay implementations. try 2.22

**Comment by bootsofglory** [comment]
The issue still persists in both 2.22 and 2.23. The speaker picture is playing music but home assistant does not consider it to be playing and does not show metadata.

<img width="381" height="387" alt="Image" src="https://github.com/user-attachments/assets/3c3d4cc2-7779-4b1d-827a-2efa34c82f55" />

**Comment by mjcumming** [comment]
ok, 2.25 should fix this - it's a battle between http and upnp metadata....

**Comment by bootsofglory** [comment]
No change with 2.25 unfortunately.

**Comment by mjcumming** [comment]
I'll need the diagnostics and logs

**Comment by bootsofglory** [comment]
Just tried 2.27, still no change. Debug logs attached.

[home-assistant_wiim_2025-11-12T17-07-18.871Z.log](https://github.com/user-attachments/files/23505590/home-assistant_wiim_2025-11-12T17-07-18.871Z.log)

**Comment by mjcumming** [comment]
I had to do a complete code refactor and separate the business logic from the integration logic - it is now ready for testing. Let's start over with the new code base.
