### ISSUE TITLE
[Question]: Is grouping Audio Pro Gen1 speakers supported?

### ISSUE THREAD

**Issue by juhavt** [mjcumming/wiim#129]
### Pre-submission Checklist

- [x] I have checked the documentation and troubleshooting guide
- [x] I have searched existing issues for similar questions

### Question Category

Multiroom/Grouping

### Question

It seems that the old Linkplay integration (https://github.com/nagyrobi/home-assistant-custom-components-linkplay) does not work anymore with the HA Core update 2025.11.

I have used it with the old Audio Pro Gen1 speaker (Audio Pro A26, C10, C5a).

So my question: are these speakers supported by this integration to join them in a group?

### What I've Tried

I tried the official Linkplay integration and this Wiim integration. They both discover the old Gen1 speakers (Audio Pro A26, C10, C5a) but the media_player.join action does not seem to do anything. Nothing specific in the logs.

### Integration Version

v1.0.29

### WiiM Device Model

Audio Pro A26, C10, C5a

**Comment by mjcumming** [comment]
I reviewed the old code base for the join/unjoin and added it to the project - give it a try in .30 rel.

**Comment by juhavt** [comment]
Thank you for fast fix. Unfortunately, now I cannot pick the target device for the `media_player.join` action when using the GUI picker. If I write the code manually in yaml I get the following error in the log:

```
2025-12-02 19:14:26.814 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Entity media_player.a26 does not support action media_player.join
2025-12-02 19:14:26.815 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139946609264256] Entity media_player.a26 does not support action media_player.join
```

The action code:
```
action: media_player.join
target:
  entity_id: media_player.a26
data:
  group_members:
    - media_player.c10
    - media_player.c5a

```

<img width="1278" height="695" alt="Image" src="https://github.com/user-attachments/assets/b9534e1d-ca41-4d7e-8f07-e21b00f06187" />

**Comment by mjcumming** [comment]
ok, some fixes in .35 - let me know - i can only try old code with nothing to test against.

**Comment by shpongledsummer** [comment]
Since I’m also using the older Audio Pro models (C10, C5, C3), I tested version 0.35 as well. Here are my results:

- Grouping is much faster now, almost as quick as the old LinkPlay integration. It takes about five seconds for the state to show up in the frontend, which is a huge improvement and makes it almost practical to group players directly from a frontend card.

- When trying to add a device to an existing group, I get errors saying “Player is already in a group.” It eventually works after a few attempts, but it looks like the grouped state is not being reported correctly, which is causing these errors.


Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:323
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 12:45:23 (3 Vorkommnisse)
Zuletzt protokolliert: 12:47:06

[140076017174464] Error during service call to script.linkplay_gewahlter_lautsprecher_dynamisch_gruppieren: Failed to add player to group: Player 192.168.178.38 is already in a group
[140076017174464] Error during service call to script.linkplay_gewahlter_lautsprecher_dynamisch_gruppieren: Failed to add player to group: Player 192.168.178.41 is already in a group
[140076017174464] Error during service call to media_player.join: Failed to add player to group: Player 192.168.178.38 is already in a group

**Comment by mjcumming** [comment]
.38 should solve this - timing maybe different in these older players making it hard to nail it down.

**Comment by shpongledsummer** [comment]
I've been testing the newest version since yesterday and overall it’s great! most major issues with my audio pro speakers are resolved, and this is the first version I can fully use again with my setup since a few weeks.

However, I’m still seeing a problem related to speaker grouping: When I try to add an additional speaker to an existing group, the integration removes the current slave speaker instead of simply adding the new one. I'm not sure whether this is caused by an issue in the integration itself or if I need to update my grouping scripts. It also works sometimes anyway.

Log shows this error:

```
Logger: custom_components.wiim.media_player
Source: custom_components/wiim/media_player.py:873
Integration: WiiM
First occurred: 15:35:23 (2 occurrences)
Last logged: 15:36:23

Failed to join player to group: Player 192.168.178.41 is already in a group
Failed to join player to group: Player 192.168.178.38 is already in a group
```


And this is the action i use to dyanmically group speakers based on variables:

```
action: media_player.join
data:
  group_members: |
    {% if target_speaker is string %}
      {{ target_speaker.split(',') }}
    {% else %}
      {{ target_speaker }}
    {% endif %}
target:
  entity_id: "{{ selected_speaker }}"
```
